const crypto = require('crypto');
const fs = require('fs');
const prompt = require('prompt-sync')({sigint: true});
const publicKey = fs.readFileSync('./Key_Pair/public.pem',encoding = 'utf8');
const data = prompt('enter data : ');
const signature = prompt('enter signature : ');
const verify = crypto.createVerify('SHA256');
verify.update(data);
verify.end();
console.log(verify.verify(publicKey, signature));
